# Generated by Django 4.2.7 on 2023-11-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orders_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='deliverBefore',
            new_name='deliver_before',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='distance',
            new_name='distance_to',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='serviceFee',
            new_name='goods_value',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='transportFee',
            new_name='service_fee',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='valueOfGoods',
            new_name='transport_fee',
        ),
    ]
