# Generated by Django 4.2.7 on 2023-11-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
